# Railway deployment configuration
[build]
builder = "DOCKERFILE"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Environment variables will be set in Railway dashboard:
# - PORT (automatically set by Railway)
# - FLASK_ENV=production